spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imagelite
    username: root
    password: 131497
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
